# Concetti chiave {#sec-basics}

La *data science* si pone all'intersezione tra statistica e informatica. La statistica è un insieme di metodi utilizzati per estrarre informazioni dai dati; l'informatica implementa tali procedure in un software. In questo Capitolo vengono introdotti alcuni concetti chiave.

## Popolazioni e campioni

*Popolazione.* L'analisi dei dati inizia con l'individuazione delle unità portatrici di informazioni circa il fenomeno di interesse. Si dice popolazione (o universo) l'insieme $\Omega$ delle entità capaci di fornire informazioni sul fenomeno oggetto dell'indagine statistica. Possiamo scrivere $\Omega = \{\omega_i\}_{i=1, \dots, n}= \{\omega_1, \omega_2, \dots, \omega_n\}$, oppure $\Omega = \{\omega_1, \omega_2, \dots \}$ nel caso di popolazioni *finite* o *infinite*, rispettivamente. Gli elementi $\omega_i$ dell'insieme $\Omega$ sono detti *unità statistiche*.

::: callout-tip
Se la notazione che uso qui non è chiara, si veda l'appendice per un ripasso delle nozioni di base della teoria degli insiemi.
:::

L'obiettivo principale della ricerca psicologica, sia nelle ricerche sperimentali che in quelle osservazionali, è quello di studiare i fenomeni psicologici in una data popolazione. È quindi necessario essere molto chiari su quale sia la popolazione di interesse (ovvero, la popolazione a cui si applicano i risultati della ricerca). La popolazione di interesse può essere *reale* (ad esempio, tutte le persone che si trovavano nella città di Hiroshima al momento del bombardamento atomico e sono sopravvissute per un anno) o *ipotetica* (ad esempio, tutte le persone depresse che possono essere sottoposte ad un intervento psicologico). Il ricercatore deve sempre essere in grado di determinare se un determinato individuo appartiene o meno alla popolazione in esame.

Una *sotto-popolazione* è una popolazione che soddisfa delle proprietà ben definite. Ad esempio, potremmo essere interessati alla sotto-popolazione degli uomini di età inferiore ai 30 anni o alla sotto-popolazione dei pazienti depressi che sono stati sottoposti ad uno specifico intervento psicologico. Molte domande scientifiche si pondono il problema di descrivere le differenze tra sotto-popolazioni -- ad esempio, il confronto tra un gruppo sottoposto a psicoterapia e un gruppo di controllo per determinare l'efficacia di un trattamento.

*Campione.* Un sottoinsieme della popolazione, ovvero un insieme di elementi $\omega_i$, viene chiamato *campione*. Ciascuna unità statistica $\omega_i$ (abbreviata con u.s.) è portatrice dell'informazione che verrà rilevata mediante un'operazione di misurazione. Un campione è dunque un sottoinsieme di una popolazione utilizzato per conoscere una tale popolazione.

A differenza di una sotto-popolazione definita in base a criteri chiari, un campione viene generalmente selezionato tramite un procedura casuale. Il *campionamento casuale* consente al ricercatore di trarre conclusioni sulla popolazione e, soprattutto, di quantificare l'incertezza sui risultati. Il campione usato in un sondaggio è un esempio di campione casuale. Si noti però che molti studi osservazionali non utilizzano dei dati campionati casualmente. Un *campione di convenienza* può essere costituito, ad esempio, una coorte di studenti selezionati in un unico istituto.

Indipendentemente da come vengono ottenuti i dati, il ricercatore si deve sempre porre il problema della *rappresentatività statistica* del campione, ovvero deve chiedersi se il campione è in grado di rispecchiare e di riprodurre senza distorsioni le caratteristiche di interesse della popolazione. Il metodo più semplice che garantisce la rappresentatività è dato dalla casualità della selezione delle unità statistiche del campione. In psicologia, tuttavia, molto spesso i ricercatori non hanno a disposizione gli strumenti (si legga, i fondi) per utilizzare la tecnica del campionamento casuale nelle loro ricerche.

## Variabili e costanti

Una *variabile* è qualsiasi proprietà o descrittore che può assumere più valori (numerici o categoriali). Si può pensare ad una variabile come la domanda di cui il valore dell'u.s. è la risposta. Ad esempio, "Qual è l'età di questo partecipante?" "19 anni". Qui, "età" è la variabile e "19" è il suo valore.

La probabilità che la variabile $X$ assuma il valore $x$ si scrive $P(X = x)$. Questo è spesso abbreviato in $P(x)$. Si noti che $P(X = 19)$ è interpretato come la probabilità che un individuo selezionato a caso dalla popolazione abbia 19 anni. Possiamo anche esaminare la probabilità *congiunta* di più valori contemporaneamente; ad esempio, la probabilità di $X = x$ e $Y = y$ è scritta $P(X = x, Y = y)$ o $P(x, y)$. La nozione di "variabile" si contrappone alla nozione di "costante", ovvero ad una proprietà che rimane invariante per tutte le unità statistiche.

Si dice *modalità* ciascuna delle varianti con cui una variabile statistica può presentarsi. Definiamo *insieme delle modalità* di una variabile statistica l'insieme $M$ di tutte le possibili espressioni con cui la variabile può manifestarsi. Le modalità osservate e facenti parte del campione si chiamano *dati*.

::: {#exm-keys-1}
Supponiamo che il fenomeno studiato sia l'intelligenza. In uno studio, la popolazione potrebbe corrispondere all'insieme di tutti gli italiani adulti. La variabile considerata potrebbe essere il punteggio del test standardizzato WAIS-IV. Le modalità di tale variabile potrebbero essere 112, 92, 121, ... Tale variabile è di tipo quantitativo discreto.
:::

::: {#exm-keys-2}
Supponiamo che il fenomeno studiato sia il compito Stroop. La popolazione potrebbe corrispondere all'insieme dei bambini dai 6 agli 8 anni. La variabile considerata potrebbe essere il reciproco dei tempi di reazione in secondi. Le modalità di tale variabile potrebbero essere 1.93, 2.35, 1.32, 1.49, 1.62, 2.93, ... La variabile è di tipo quantitativo continuo.
:::

::: {#exm-keys-3}
Supponiamo che il fenomeno studiato sia il disturbo di personalità. La popolazione potrebbe corrispondere all'insieme dei detenuti nelle carceri italiane. La variabile considerata potrebbe essere l'assessment del disturbo di personalità tramite interviste cliniche strutturate. Le modalità di tale variabile potrebbero essere i Cluster A, Cluster B, Cluster C descritti dal DSM-V. Tale variabile è di tipo qualitativo.
:::

### Variabili casuali

Il termine *variabile* usato nella statistica è equivalente al termine *variabile casuale* usato nella teoria delle probabilità. Lo studio dei risultati degli interventi psicologici è lo studio delle variabili casuali che misurano questi risultati. Una variabile casuale cattura una caratteristica specifica degli individui nella popolazione e i suoi valori variano tipicamente tra gli individui. In teoria, ogni variabile casuale può assumere una gamma di possibili valori sebbene, in pratica, osserviamo un valore specifico per ogni individuo. Useremo lettere maiuscole come $X$ e $Y$ per fare riferiremo alle variabili casuali; useremo lettere minuscole come $x$ e $y$ quando faremo riferimento ai valori assunti da una variabile casuale in una specifica circostanza.

::: callout-note
Che differenza c'è tra una variabile casuale e una variabile statistica? La differenza tra questi due concetti può essere descritta dall'incertezza epistemica del ricercatore. Supponiamo, ad esempio, che l'*esperimento casuale* sia il lancio di un dado e la variabile di interesse $X$ sia l'esito del lancio del dado. Poniamo che in una prova dell'esperimento casuale, ovvero in uno specifico lancio, la variabile $X$ assuma il valore 5. Prima del lancio del dado, la variabile $X$ è una *variabile casuale* (il ricercatore sa che $X$ può assumere i valore 1, ..., 6, ma non conosce lo specifico valore che verrà osservato dopo il lancio); dopo il lancio del dado, avendo osservato $X$ = 5, la variabile $X$ diventa una *variabile statistica*, ovvero costituisce un dato del campione di osservazioni.
:::

## Statistica

Una statistica è una qualsiasi funzione del campione di una variabile casuale.

::: callout-note
Esempi di statistiche sono la media campionaria, la mediana campionaria, la varianza, ecc. Ma, per la definizione precedente, qualunque funzione arbitraria del campione costituisce una statistica: per esempio, il rapporto tra il valore minimo e il logaritmo del valore massimo del campione. Pur essendo insensato, un tale valore è una statistica del campione.
:::

### Variabili indipendenti e variabili dipendenti

Un primo compito fondamentale in qualsiasi analisi dei dati è l'identificazione delle variabili *dipendenti* ($Y$) e delle variabili *indipendenti* ($X$). Le variabili dipendenti sono anche chiamate variabili di esito o di risposta e le variabili indipendenti sono anche chiamate predittori o covariate. Ad esempio, nell'analisi di regressione, che esamineremo in seguito, la domanda centrale è quella di capire come varia $Y$ al variare di $X$. Più precisamente, la domanda che viene posta è: se viene mutato il valore della variabile indipendente $X$, quale conseguenza ne deriva per la variabile dipendente $Y$? In parole povere, le variabili indipendenti e dipendenti sono analoghe a "cause" ed "effetti", laddove le virgolette qui usate sottolineano che questa è solo un'analogia e che la determinazione delle cause può avvenire soltanto mediante l'utilizzo di un appropriato disegno sperimentale e di un'adeguata analisi statistica.

Se una variabile è una variabile indipendente o dipendente dipende dalla domanda di ricerca. A volte può essere difficile distinguere le variabili dipendenti dalle variabili indipendenti, in particolare quando siamo specificamente interessati ai rapporti di causa/effetto. Ad esempio, supponiamo di indagare l'associazione tra esercizio fisico e insonnia. Vi sono evidenze che l'esercizio fisico (fatto al momento giusto della giornata) può ridurre l'insonnia. Ma l'insonnia può anche ridurre la capacità di una persona di fare esercizio fisico. Non è dunque facile capire quale sia la causa e quale sia l'effetto, ovvero quale sia la variabile dipendente e quale la variabile indipendente. La possibilità di identificare il ruolo delle variabili (dipendente/indipendente) dipende dalla nostra comprensione del fenomeno in esame.

::: {#exm-keys-4}
Uno psicologo convoca 120 studenti universitari per un test di memoria. Prima di iniziare l'esperimento, a metà dei soggetti viene detto che si tratta di un compito particolarmente difficile; agli altri soggetti non viene data alcuna indicazione. Lo psicologo misura il punteggio nella prova di memoria di ciascun soggetto. In questo esperimento, la variabile indipendente è l'informazione sulla difficoltà della prova. La variabile indipendente viene manipolata dallo sperimentatore assegnando i soggetti (di solito in maniera causale) alla condizione (modalità) "informazione assegnata" o alla condizione "informazione non data". La variabile dipendente è ciò che viene misurato nell'esperimento, ovvero il punteggio nella prova di memoria di ciascun soggetto.
:::

### La matrice dei dati

Le realizzazioni delle variabili esaminate in una rilevazione statistica vengono organizzate in una *matrice dei dati*. Le colonne della matrice dei dati contengono gli insiemi dei dati individuali di ciascuna variabile statistica considerata. Ogni riga della matrice contiene tutte le informazioni relative alla stessa unità statistica. Una generica matrice dei dati ha l'aspetto seguente:

$$
D_{m,n} = 
 \begin{pmatrix}
  \omega_1 & a_{1}   & b_{1}   & \cdots & x_{1} & y_{1}\\
  \omega_2 & a_{2}   & b_{2}   & \cdots & x_{2} & y_{2}\\
  \vdots   & \vdots  & \vdots  & \ddots & \vdots & \vdots  \\
 \omega_n  & a_{n}   & b_{n}   & \cdots & x_{n} & y_{n}
 \end{pmatrix}
 $$

dove, nel caso presente, la prima colonna contiene il nome delle unità statistiche, la seconda e la terza colonna si riferiscono a due *mutabili* statistiche (o variabili categoriali; $A$ e $B$) e ne presentano le modalità osservate nel campione mentre le ultime due colonne si riferiscono a due *variabili* statistiche ($X$ e $Y$) e ne presentano le modalità osservate nel campione. Generalmente, tra le unità statistiche $\omega_i$ non esiste un ordine progressivo; l'indice attribuito alle unità statistiche nella matrice dei dati si riferisce semplicemente alla riga che esse occupano.

## Effetto

L'*effetto* è una qualche misura dei dati. Dipende dal tipo di dati e dal tipo di test statistico che si vuole utilizzare. Ad esempio, se viene lanciata una moneta 100 volte e esce testa 66 volte, l'effetto sarà 66/100. Diventa poi possibile confrontare l'effetto ottenuto con l'effetto nullo che ci si aspetterebbe da una moneta bilanciata (50/100), o con qualsiasi altro effetto che può essere scelto. La *dimensione dell'effetto* si riferisce alla differenza tra l'effetto misurato nei dati e l'effetto nullo (di solito un valore che ci si aspetta di ottenere in base al caso soltanto).

## Stima e inferenza

La stima è il processo mediante il quale il campione viene utilizzato per conoscere le proprietà di interesse della popolazione. Ad esempio, la media campionaria è una stima naturale della media della popolazione e la mediana campionaria è una stima naturale della mediana della popolazione. Quando si discute la stima di una proprietà della popolazione (a volte indicata come parametro della popolazione) o la stima della *distribuzione* di una variabile casuale (ovvero la probabilità che la variabile assuma qualsiasi valore in un dato intervallo), si fa riferimento all'utilizzo dei dati osservati per conoscere le proprietà di interesse della popolazione. L'inferenza statistica è il processo mediante il quale le stime campionarie vengono utilizzate per rispondere alle domande della ricerca e per valutare specifiche ipotesi relative alla popolazione. Nell'ultima parte di questa dispensa discuteremo le procedure bayesiane dell'inferenza e illustreremo i limiti dell'inferenza frequentista.

<!-- ## Parametri e modelli -->

<!-- Ogni variabile casuale ha una *distribuzione* che descrive la probabilità che la variabile assuma qualsiasi valore in un dato intervallo.[^001_key_notions-1] Senza ulteriori specificazioni, una distribuzione può fare riferimento a un'intera famiglia di distribuzioni. I parametri, tipicamente indicati con lettere greche come $\mu$ e $\alpha$, ci permettono di specificare di quale membro della famiglia stiamo parlando. Quindi, si può parlare di una variabile casuale con una distribuzione Normale, ma se viene specificata la media $\mu = 100$ e la varianza $\sigma^2 = 15^2$, allora viene individuata una specifica distribuzione Normale -- nell'esempio, la distribuzione del quoziente di intelligenza. -->

<!-- [^001_key_notions-1]: In questo e nei successivi paragrafi di questo capitolo introduco gli obiettivi della *data science* utilizzando una serie di concetti che saranno chiariti solo in seguito. Questa breve panoramica risulterà dunque solo in parte comprensibile ad una prima lettura e serve solo per definire la *big picture* dei temi trattati in questo insegnamento. Il significato dei termini qui utilizzati sarà chiarito con maggiore precisione nei capitoli successivi. -->

<!-- I metodi statistici parametrici specificano la famiglia delle distribuzioni e quindi utilizzano i dati per individuare, stimando i parametri, una specifica distribuzione all'interno della famiglia di distribuzioni ipotizzata. Se $f$ è la PDF di una variabile casuale $Y$, l'interesse può concentrarsi sulla sua media e varianza. Nell'analisi di regressione, ad esempio, cerchiamo di spiegare come i parametri di $f$ dipendano dalle covariate $X$. Nella regressione lineare classica, assumiamo che $Y$ abbia una distribuzione normale con media $\mu = \mathbb{E}(Y)$, e stimiamo come $\mathbb{E}(Y)$ dipenda da $X$. Poiché molti esiti psicologici non seguono una distribuzione normale, verranno introdotte distribuzioni più appropriate per questi risultati. I metodi non parametrici, invece, non specificano una famiglia di distribuzioni per $f$. In queste dispense faremo riferimento a metodi non parametrici quando discuteremo la statistica descrittiva. -->

<!-- Il termine *modello* è onnipresente in statistica e nella *data science*. Un modello statistico include le ipotesi e le specifiche matematiche relative alla distribuzione della variabile casuale di interesse. Il modello dipende dai dati e dalla domanda di ricerca, ma raramente è unico; nella maggior parte dei casi, esiste più di un modello che potrebbe ragionevolmente usato per affrontare la stessa domanda di ricerca avendo a disposizione i dati osservati. La domanda di cosa costituisca un buon modello è una domanda su cui torneremo ripetutamente in questa dispensa. -->

<!-- ::: {#exm-keys-5} -->

<!-- Ad esempio, nella previsione delle aspettative future dei pazienti depressi che discuteremo in seguito [@zetschefuture2019], la specifica del modello include l'insieme delle covariate candidate, l'espressione matematica che collega i predittori con la variabile dipendente e qualsiasi ipotesi sulla distribuzione della variabile dipendente. -->

<!-- ::: -->

## Modelli psicologici

Il termine *modello* è onnipresente in statistica e nella *data science*. Un modello statistico include le ipotesi e le specifiche matematiche relative alla distribuzione della variabile casuale di interesse. Il modello dipende dai dati e dalla domanda di ricerca, ma raramente è unico; nella maggior parte dei casi, esiste più di un modello che potrebbe ragionevolmente usato per affrontare la stessa domanda di ricerca avendo a disposizione i dati osservati. Il problema di cosa costituisca un buon modello è una domanda su cui torneremo ripetutamente in questa dispensa.

Un modello psicologico di un qualche aspetto del comportamento umano o della mente ha le seguenti proprietà:

1.  descrive le caratteristiche del comportamento in questione,
2.  formula predizioni sulle caratteristiche future del comportamento,
3.  è sostenuto da evidenze empiriche,
4.  deve essere falsificabile (ovvero, in linea di principio, deve potere fare delle predizioni su aspetti del fenomeno considerato che non sono ancora noti e che, se venissero indagati, potrebbero portare a rigettare il modello, se si dimostrassero incompatibili con esso).

L'analisi dei dati si pone l'obiettivo di valutare un modello psicologico mediante strumenti statistici.
