# Per liberarvi dai terrori preliminari {#sec-calculus}

Fornisco qui la traduzione (ottenuta con Google Translate, con piccole modifiche) del primo capitolo di [Calculus made easy](https://calculusmadeeasy.org/1.html).

Il terrore preliminare, che impedisce alla maggior parte dei ragazzi di quinta anche solo di tentare di imparare l'analisi, può essere abolito una volta per tutte semplicemente affermando qual è il significato -- in termini di buon senso -- dei due simboli principali che sono usati nell'analisi matematica.

Questi terribili simboli sono:

1.  $d$ che significa semplicemente "un po' di".

Quindi $\operatorname{d}\!x$ significa un po' di $x$; o $\operatorname{d}\!u$ significa un po' di $u$. I matematici pensano che sia più educato dire "un elemento di" invece di "un po' di". Fai come ti pare. Ma scoprirai che questi piccoli pezzi (o elementi) possono essere considerati indefinitamente piccoli.

2.  $\int$ che è semplicemente una S allungata, e può essere chiamata (se volete) "la somma di".

Quindi $\int \operatorname{d}\!x$ significa la somma di tutti i pezzettini di $x$; oppure $\int \operatorname{d}\!t$ significa la somma di tutti i pezzettini di $t$. I matematici chiamano questo simbolo "l'integrale di". Ora qualsiasi sciocco può vedere che se $x$ è considerato come composto da tanti piccoli pezzetti, ognuno dei quali è chiamato $\operatorname{d}\!x$, se li sommi tutti insieme ottieni la somma di tutti i $\operatorname{d}\!x$, (che è la stessa cosa dell'insieme di $x$). La parola "integrale" significa semplicemente "il tutto". Se pensi alla durata di un'ora, puoi (se vuoi) pensarla come suddivisa in 3600 piccoli pezzetti chiamati secondi. L'insieme dei 3600 pezzetti sommati fa un'ora.

Quando vedrete un'espressione che inizia con questo simbolo terrificante, d'ora in poi saprete che è stato messo lì semplicemente per darvi l'istruzione che ora dovete eseguire (se potete) l'operazione di sommare tutti i piccoli pezzetti che sono indicati dai simboli che seguono.

È tutto.
