# Parte 7: Inferenza frequentista {#sec-frequentist-inference}

L'approccio frequentista è basato sull'idea di probabilità quale frequenza relativa. Tale approccio immagina che un determinato esperimento casuale venga ripetuto infinite volte e si chiede come si distribuiscono i risultati ottenuti. Nel @sec-law-large-numbers viene presentata la legge dei grandi numeri. Nel @sec-interv-conf viene presentata la nozione di intervallo fiduciale; verrà discussa l'interpretazione corretta di questo concetto e verranno presentati alcune diffusi fraintendimenti. Nel @sec-sampling-distr-mean viene discussa la distribuzione campionaria della media, un esempio della logica che sta alla base dell'inferenza frequentista. Nel @sec-stat-significance viene presentata la controversa procedura di test di ipotesi statistiche. Nel @sec-mean-comp viene presentata la procedura di confronto tra medie, una delle applicazioni più popolari dell'inferenza frequentista. Nel @sec-limits-inf-freq verranno discussi i limiti dell'inferenza frequentista.
